### ISSUE TITLE
Encoding Very Slow To Start

### ISSUE THREAD

**Issue by BarryBennett** [lordmulder/LameXP#101]
Having issues with encoding not wanting to start.  Have used the software for years and never observed this issue before.  Basically you load up some files to convert, set the various encoding options, and click the Encode Now button.  Several songs change to "starting..." status and then nothing happens.  Running the debug console shows several process threads starting but nothing after that.  Weird thing is that if you wait long enough (many minutes) then things seem to start and then encoding goes normally with about 1-2 seconds per song.  Have noticed that normal behavior will continue for awhile (several hundred songs) and then it goes back to the "starting..." status where everything seems paused again.  During the pause time the CPU usage is usually low (0-1 %) and the machine is otherwise working fine and very responsive.  Have noticed this issue on multiple Windows 10 machines so it is not specific to a single installation.  There are times when the problem does not occur with the same exact set of songs and settings.  Have not come to any conclusion on what makes it appear or how to solve it other than keep restarting the software and trying again.

**Comment by lordmulder** [comment]
Well, this would indicate that LameXP is waiting for the encoder sub-process to start, but it (apparently) never does start 😕 

...or takes extremely long to do so.

If you look in your [process explorer](https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer), do you see the encoder process (e.g. `lame.exe`) or just the main `LameXP.exe` process?

-------

Also, does that happen with the ***latest*** release? (version 4.19)

If so: Does it **also** happen with the *previous* release (version 4.18), or is this a "new" problem in version 4.19?

-------

Do you have any so-called "anti-virus" software installed on your system?

If so: After eradicating the "anti-virus" software from your system – _please try that for test_ – does the problem still occur?

-------

Since you are referring to the "Debug" console:

Be aware that clicking in the console window may trigger "selection mode". This can happen unintentionally. But, for as long as the console window still is in "selection mode", the whole application (including GUI) will ***freeze***. This is a Windows "feature" that I cannot do anything about. Press enter in the console window in order to end "selection mode" and thus un-freeze the application.

Regards.
