### ISSUE TITLE
Tablet Version Mismatch

### ISSUE THREAD

**Issue by RedAISkye** [lordmulder/LameXP#104]
![Screenshot](https://i.imgur.com/N6PIHDw.png)

As you can see by the screenshot, I'm getting this error every time I start **LameXP.exe**

**Comment by lordmulder** [comment]
This error message definitely is **not** created by LameXP. It must be caused by something else 😏 

A quick Google search seems to indicate that this may be related to Wacom tablet drivers:
https://clearps.com/photoshop-discussions/threads/60310-suppress-quot-tablet-version-mismatch-quot-dialog-box/
