### ISSUE TITLE
Old refalac

### ISSUE THREAD

**Issue by xtemp09** [lordmulder/LameXP#11]
I have an m4a file (ALAC), created with ffmpeg. If I try to convert it with the latest LameXP into m4a (AAC), I get error - lxp_refalac.exe exits with code (0xC0000374). If I try the command which is used by LameXP (lxp_refalac.exe -D 1.m4a -o XXX.wav), the process freezes. However, if I use the latest refalac (1.47), it goes just fine.

The version of LameXP is the latest - LameXP v4.11 Final · Build #1700. (lxp_refalac says that it's 0.56)

Please, update refalac to the latest version.

If needed, I can upload an m4a file which causes crash.

**Comment by lordmulder** [comment]
0xC0000374 is the NT_STATUS for "heap corruption", so something bad has happened in refalac. Don't know if this is because your file is corrupt/invalid or because of something else. But, in any case, refalac shouldn't crash this way! I will consider updating refalac to the latest version...

**Comment by xtemp09** [comment]
Might I ask, when are you going to update it? I would be very grateful if you could simply replace lxp_refalac and release it as beta version or as a build of the current version.

**Comment by lordmulder** [comment]
LameXP v4.11 has been released recently, so a new release is **not** imminent at this time. But I can send you a test build with latest refalac included. Can't promise anything, but maybe I can do this tonight.

**Comment by xtemp09** [comment]
Thanks in advance. I want to convert my entire lossless library into something edible to my phone.

**Comment by lordmulder** [comment]
Okay, you can try with the new **test** build here:
https://www.sendspace.com/file/2hqofw

**Comment by xtemp09** [comment]
Many thanks, that works like a charm. One more question before it's closed: how can I set output format m4a instead of mp4? My phone easily plays mp4, but it treats it like a video file (even if I play I can't set it as a ringtone). If I rename the file to m4a, I can set it as a ringtone.

**Comment by xtemp09** [comment]
In addition, before the issue is closed, could you consider changing AAC encoder to FDK AAC?

FDK AAC is compatible with GPL, but it cannot be compiled into a binary. Since LameXP needs another binary to be downloaded (rather outdated Nero encoder/decoder), it won't make any difference to the program what external tool to use, but it will make noticeable difference in quality to users.

I would be grateful if you could consider both my proposals.

**Comment by lordmulder** [comment]
> Many thanks, that works like a charm. One more question before it's closed: how can I set output format m4a instead of mp4?

There is no such thing as "M4A" file. The file format is **MP4**. Or, more specifically, *MPEG-4 Part 14* (aka *ISO/IEC 14496-14*). Whether you call this file "something.*mp4*" or "something.*m4a*" or even "something.*doc*" doesn't change anything about the file's content. It's still a file in MP4 format! Using certain file name "extensions" for certain file types is nothing but a naming convention; a convenience for the user. Technically, it is irrelevant. But if there is any "correct" file extension for MP4 files, then it is ".mp4", **not** ".m4a" or whatever. So we use the proper extension here.

I know that some applications will assume the file format based on the file name, rather than analyzing the file header. This is plain wrong and needs to be fixed in the individual application.

**Comment by lordmulder** [comment]
> In addition, before the issue is closed, could you consider changing AAC encoder to FDK AAC?

Changing? Probably no! We currently support Nero AAC as well as QAAC (iTunes/QuickTime AAC encoder) and FhgAac (Winamp AAC encoder). Though the latter is probably dead, now that Winamp is no more. Adding FDK AAC as another option is quite possible. But is there a proper *stand-alone* CLI encoder for FDK AAC? I only know that FDK AAC can be use to create AAC streams in FFmpeg. But using FFmpeg here is like taking a sledgehammer to crack a nut...

**Comment by xtemp09** [comment]
I'm very much aware of identity between mp4 and m4a formats and know that the difference lies only in file extension. Nevertheless, renaming long list of files requires batch rename tool, which the majority users don't have. I didn't say that to use m4a is right, but my default UI doesn't accept an mp4 as an audio file, that's it. This is a common case, especially when it comes to Android. Apple started using m4a as an audio-only media format, according to Wikipedia:
https://en.wikipedia.org/wiki/MPEG-4_Part_14#.MP4_versus_.M4A
Perhaps, it's discreetly to trust the creators of the format.

Regarding FDK AAC, there is a free simple command-line encoding tool, fdkaac, which I put forward for your consideration as a replacement for NeroEnc:
http://wiki.hydrogenaud.io/index.php?title=Fraunhofer_FDK_AAC#fdkaac

The Fraunhofer FDK AAC is a world-famous AAC encoder known for high-quality sound when it comes to lower bitrates.
I hope high-quality AAC will come to LameXP.

Regarding to ffmpeg, I think it's a great idea to use ffmpeg as a decoder or, sometimes, as an encoder tool. Compilation without numerous libraries, e.g. concerning video conversion (x264, Blu-ray etc), transforms the hammer into a fast light-weight tool. However, it's for you to decide, I need only a good AAC.

**Comment by lordmulder** [comment]
> I'm very much aware of identity between mp4 and m4a formats and know that the difference lies only in file extension. Nevertheless, renaming long list of files requires batch rename tool, which the majority users don't have. I didn't say that to use m4a is right, but my default UI doesn't accept an mp4 as an audio file, that's it. This is a common case, especially when it comes to Android.

Still I don't like to have an "output M4A" option, as it only spreads and/or strengthens the *false* idea that MP4 and M4A are two different file formats, when it's actually the exactly same thing. When I need to batch rename files, I just use *Total Commander* for this purpose, which works great. Anyway, maybe I can extend the existing LameXP "auto-rename" feature, so that the file extension can be "overwritten" too.

**Comment by lordmulder** [comment]
> regarding FDK AAC, there is a free simple command-line encoding tool, fdkaac, which I put forward for your consideration as a replacement for NeroEnc:
> http://wiki.hydrogenaud.io/index.php?title=Fraunhofer_FDK_AAC#fdkaac

I will have a look at this tool. Maybe it can be added to LameXP as another option.

> The Fraunhofer FDK AAC is a world-famous AAC encoder known for high-quality sound when it comes to lower bitrates.
> I hope high-quality AAC will come to LameXP.

As said before, we already support *QAAC* (Apple) and *FhgAac* (Winamp) in addition to *Nero AAC*:
http://lamexp.sourceforge.net/doc/Manual.html#install-the-aac-encoder

**Comment by xtemp09** [comment]
The new refalac works.

**Comment by lordmulder** [comment]
Here is a new version with **experimental** lib-fdkaac encoding support:
https://www.sendspace.com/file/ukaqkw

You will also need the "fdkaac" *add-in* from here:
https://www.sendspace.com/file/asa8tb

**Comment by xtemp09** [comment]
Maybe this is me, maybe this is Isgaard, but the sound is impeccable. Tested it on VBR/CBR, high/low bitrate/quality. Sampling rate stays the same in contrast to the other AAC encoders. Thanks for implementing it.

According to that message:
https://lists.ffmpeg.org/pipermail/ffmpeg-devel/2013-February/139156.html

This encoder cannot be statically linked, but can be redistributed as a binary. I propose to consider its distribution along with LameXP. If you hate this idea, automatic download of AAC encoder (any) can be big help to end user.

**Comment by lordmulder** [comment]
> Maybe this is me, maybe this is Isgaard, but the sound is impeccable. Tested it on VBR/CBR, high/low bitrate/quality. Sampling rate stays the same in contrast to the other AAC encoders. Thanks for implementing it.

About the *sampling rate* issue:
The sampling rate simply defines the maximum frequency that can be represented. According to [Nyquist-Shannon theorem](http://en.wikipedia.org/wiki/Nyquist%E2%80%93Shannon_sampling_theorem) the highest frequency that can be represented is ``N/2``, where ``N`` is the sampling frequency. So at sampling rate of 44100 Hz the highest frequency is 22050 Hz, at sampling rate of 22050 Hz the highest frequency is 11025 Hz, and so on. Consequently, *resampling* to a lower sampling rate effectively is a "low-pass" filter, i.e. it removes the higher frequencies. Some encoders to this at the lower bitrates (LAME MP3 does it too!), because at the lower bitrates you have to sacrifice *something*, no matter what. And thus getting rid of the higher frequencies, which are barely audible for a normal human listener (if at all), makes a lot of sense then. It improves overall result, at these bitrates.

Now in AAC there is another thing to consider:
**HE-AAC** is nothing but the "normal" **LC-AAC** combined with **SBR** (Spectral Bandwidth Replication). And SBR is simply a *pre-processor* that reduces sampling rate to 1/2 *before* sending the audio data to the actual AAC encoder. After *decoding*, SBR will then upsample back to the original sampling rate again and "reconstruct" the highest frequencies that have been lost. SBR can be used with any encoder (MP3 + SBR is called "mp3PRO"), but when used with AAC it's called "HE-AAC". This means that a HE-AAC stream can be decoded with **any** AAC decoder, but only a *HE-AAC-enabled* decoder you get back the full sampling rate. Standard LC-AAC decoder would decode the stream just fine, but at 1/2 of the sampling rate.

**Comment by lordmulder** [comment]
> This encoder cannot be statically linked, but can be redistributed as a binary. I propose to consider its distribution along with LameXP. If you hate this idea, automatic download of AAC encoder (any) can be big help to end user.

For the GPL it does **not** matter, whether you load a DLL at runtime or link statically - for the LPGL it *does*. But the GPL requires that, if you link against a library (may it be DLL or static) and either the main program or the library was under GPL, the *whole* "combined work" needs to be distributed under the GPL too! If this is **not** possible for some reason, because one of the components has a license that is **not** compatible with GPL (as seems to be the case with *libfdk-aac*) then the "combined work" becomes "non-redistributable". That is: Creating this "combined work" on your own machine, only for you own purposes, is fine. But you are **not** allowed to share the binary with somebody else.

**Comment by xtemp09** [comment]
Thank you for such interesting and deep review of crucial matter, however, it depends on interpretation of the license.

But I'm having an understanding that you have nothing against one-click-install. =)

Like in openSUSE - after installation it asks you if you wish to download the codecs and all you have to do is to press the button. GPL+patents are not violated.

**Comment by xtemp09** [comment]
LameXP is a great tool with which I easily converted my library. Could you consider adding m4a extension through renaming output files on "Advanced Options," in the group "Rename Pattern?" I tried "\<BaseName\>.m4a," but the output was "\<BaseName\>.m4a.mp4" anyway. =))

Input something like: "\<Ext\>=m4a" sets the output extension to m4a?

It won't violate your desire to follow standards, just a little fix to unburden end user.
