### ISSUE TITLE
Error importing cue files if filename or title is longer than 40 characters

### ISSUE THREAD

**Issue by Stony-HD** [lordmulder/LameXP#112]
If the filename of the CUE file contains more than 40 characters (and/or special characters), some tracks where not imported.
Sometimes all titles are skipped.

A similar behavior occurs when track or artist name are longer than 40 characters and/or contain special characters.
However, generally only the title is skipped without any notification or error message why they are skipped.

It should be easy to remove all special characters (or at least those that are not allowed in filenames) and truncate the folder name and title, artist name at 40 characters.

**Comment by lordmulder** [comment]
There is **no** "hard" length limit in the CUE parser. Also, there should be **no** problems with "special character", because the CUE parser is fully Unicode aware. But, of course, you have to select the correct character encoding! That is necessary, because CUE files have **no** meta-data that would indicate the character encoding. By default, we use your system's default character encoding, but you can select UTF-8 or whatever is needed...

**Comment by Stony-HD** [comment]
Thanks for the info - selecting "UTF-8" solves the problem.

But then it would be nice if you could save this setting – for example in the "Advanced Options".
Or better - in the selection dialog of the character set. E.g. with a checkbox "set as default"

**Comment by Stony-HD** [comment]
THX
