### ISSUE TITLE
Losing artist metadata

### ISSUE THREAD

**Issue by Chimel** [lordmulder/LameXP#17]
I have a rock festival album I ripped into lossless WMA. The songs have 2 artists fields, one for the compilation ("Various Artists"), one for each song (the interpret of the song). When I converted them into MP3 for mobile playback, the Album Artist field was blanked out, and the other artist field (not sure how it's called in English Windows, maybe "Recording Artist") specific to each song was replaced by the anonymous "Various Artists" value from the Album Artist field.

I looked at older conversions and it seems that the same thing happened, except that the artists were (incorrectly) filed in the "Album Artist" metadata, so this field was blanked out during the conversion, but at least the artist information was not lost because it moved from the "Album Artist" to the "Recording Artist" field. I didn't notice the problem earlier because I don't manage my music library with the MP3 files when I have corresponding lossless files, but since I convert the files in the same folder, the different values of the 2 artists fields was very visible.

In the attached screenshot, the first column was blanked out and the second contained only the useless "Various Artists" value, not the original recording artist name. I had to edit each song manually to restore the artist name, and each disc manually to reset the album artist to "Various Artists" as shown in the screenshot after this work. I would expect LameXP to convert files without changing the metadata information.
![lamexp1700](https://cloud.githubusercontent.com/assets/1156385/7538309/3b84f236-f59f-11e4-8734-4290c5f39269.png)

**Comment by lordmulder** [comment]
I think we have been through this many times before:

There is **not** that *one* standard for meta information which every file format out there complies with! Instead, every file format goes its own way. There is a famous quote that goes like *"The nice thing about standards is that there are so many of them to choose from"* - and there is much truth in this.

For example, **MP3** has *no* official (standardized) way for carrying meta information at all! So somebody invented [*ID3*](http://id3.org/id3v2.3.0), which has become kind of a de-facto standard for meta tags in MP3 files. At the same time, **AAC** streams are usually stored in an *MP4* container. So meta tags for AAC files are [*stored on the MP4 container level*](http://atomicparsley.sourceforge.net/mpeg-4files.html) – with *iTunes* setting the de-facto standard for which atoms are supported. Furthermore, **Vorbis** streams, which are stored in an *Ogg* container, use [*VorbisComment*](http://www.xiph.org/vorbis/doc/v-comment.html) to store meta information. And **Opus** streams, which are usually stored in *Ogg* container too, use a method [*similar to VorbisComment*](https://wiki.xiph.org/OggOpus#Comment_Header). Moreover, **Monkey's Audio** uses something called [*APE Tag*](http://wiki.hydrogenaud.io/index.php?title=APEv2_specification) to store meta information. This list could easily be continued, but I think you'll get the point from here...

Now it should be easy to see that "copying" the meta information is **not** a trivial task at all! First of all, we must *extract* the meta information form the original input file – from whatever meta-tag format that the input file uses. Then we need to *store* the extracted meta information internally, so we can use it later on. Finally, after the re-encoded file has been created, we need to *re-embed* the meta information that we extracted/stored before – in the meta-tag format suitable for the particular output audio format. Of course, this whole process requires **translating** the meta tags from the particular input tag format to the particular output tag format. With at least *18* supported input audio formats and at least *9* supported output audio format, this makes **162+** possible combinations that LameXP needs to be able to handle!

To put it straight: The *internal* representation of meta-data in LameXP has been designed as a "lowest common denominator" for all the various file formats that we need to deal with. And this unavoidably means that we certainly cannot retain every bit of information that may have existed in the particular input file! Among that variopus meta tags that LameXP *does* support is ``tile``, ``artist`` and ``album``. Neither does this include "Album Artist" nor "Recording Artist", as those would be way to specific.

**Comment by Chimel** [comment]
Thank you for the detailed information. I thought WMA was using ID3 too because Windows Explorer shows the same metadata fields regardless of the format, and I was able to edit these fields straight from Windows Explorer, via the files' properties.

I see now that WMA uses ASF metadata, so these fields on the newly generated LameXP files were added automatically (I didn't have to do anything to add the missing field), either as soon as the file was indexed in the Windows Media audio library, or as I entered the field's value.

Compilation albums are not the majority, especially in these album-less individual iTunes songs, so I don't care very much about this bug. I use these MP3 files for mobile playing, I use FLAC or WMA lossless to manage my audio library with the proper metadata.

**Comment by lordmulder** [comment]
> I see now that WMA uses ASF metadata, so these fields on the newly generated LameXP files were added automatically (I didn't have to do anything to add the missing field), either as soon as the file was indexed in the Windows Media audio library, or as I entered the field's value.

Yes, **WMA** streams are stored in *ASF* container, which has its own way of storing meta information. Some of the [*attributes*](https://msdn.microsoft.com/en-us/library/windows/desktop/dd743066%28v=vs.85%29.aspx) that ASF can store have an equivalent in ID3, some don't (see [here](https://msdn.microsoft.com/en-us/library/windows/desktop/dd743220%28v=vs.85%29.aspx) for details). Anyway, when converting an existing WMA file to MP3, then LameXP will detect and remember all "attributes" from the original WMA file that have an equivalent in LameXP's *internal meta data representation*. These information, and only these information, will later be re-embedded into the new MP3 file, as an ID3-Tag.

> Thank you for the detailed information. I thought WMA was using ID3 too because Windows Explorer shows the same metadata fields regardless of the format, and I was able to edit these fields straight from Windows Explorer, via the files' properties.

Windows Explorer uses [**Shell Extensions**](https://msdn.microsoft.com/en-us/library/windows/desktop/cc144067%28v=vs.85%29.aspx) to display and/or edit meta information (see the "Metadata handler" for details). So it supports *any* meta information format – provided the suitable *Shell Extension* for this particular meta information format is installed on your computer. Windows probably ships with Shell Extensions for the most widely used formats, such as MP3/ID3 and WMA/ASF, pre-installed.

> Compilation albums are not the majority, especially in these album-less individual iTunes songs, so I don't care very much about this bug.

Wouldn't call this a bug. Losing **all** meta information is the default case! The one and only reason why you are **not** losing *all* the meta information is because LameXP extracts and stores the meta information from the original input file and later re-embeds these information into the new file. If the original input file contains some meta information that doesn't fit into LameXP's *internal meta data representation*, of if the output file format simply doesn't have a way to re-embed this information, then this particular information cannot be preserved – obviously.
