### ISSUE TITLE
Double spaces in file names are shortened to one space

### ISSUE THREAD

**Issue by stsax** [lordmulder/LameXP#21]
Hi, great tool. :)

There is a minor bug...it could also be a feature.  If a file name has two spaces between two other chars, e. g.:
Artist -  Song.m4a  -> converted to .mp3 ->
Artist - Song.mp3 -> file name has changed, one space missing.

Thanks,
Stefan

**Comment by lordmulder** [comment]
Yes, it's a feature ;-)

File name strings are generally [**``simplified()``**](http://doc.qt.io/qt-4.8/qstring.html#simplified) in order to remove redundant spaces. I don't see why you would want to have two (or more) whitespace characters in a row. It's just typographically wrong and almost certainly a typo. Just like you don't put a whitespace in front of a comma or full stop, but one after the comma or full stop.

http://de.wikipedia.org/wiki/Plenk

**Comment by stsax** [comment]
Haha, right, Github changed my post. Thank you for your answer.
