### ISSUE TITLE
Opus + OGG support

### ISSUE THREAD

**Issue by xtemp09** [lordmulder/LameXP#24]
Could you add support for Opus in OGG? Opus has the best compression ever, OGG - a popular container which supports cover art and ReplayGain. I hope it will be implemented.

**Comment by lordmulder** [comment]
Opus streams are pretty much /always/ stored in Ogg container. At least 
that's what OpusEnc (and thus LameXP) creates. Note that OggOpus, i.e. 
the specification for Ogg-encapsulation of Opus streams, says that 
*.opus* is the recommended file extension.

https://wiki.xiph.org/OggOpus#Content_Type

Regards,
MuldeR

**Comment by xtemp09** [comment]
Does .opus equal .ogg? I.e. renaming will do the trick?

**Comment by lordmulder** [comment]
The file extension ist just a part of the file *name*. Renaming the file 
/never /is going to change its content (and thus it's never going to 
change its format). As explained before, the /recommended/ file 
extension for Ogg Opus files (according to the standard) is *.opus*. 
Surely, you can rename those files to *.ogg* (latest LameXP also offers 
a way to that automatically for you). Those files would still be 
perfectly valid Ogg Opus files, as the file's content hasn't changed at 
all. But, does it make much sense to use a "wrong" file extension? 
Probably not! In most cases you should stick with the "correct" file 
extension, as defined by the Ogg Opus specification.

MuldeR

**Comment by xtemp09** [comment]
Could you add cover art and ReplayGain calculation for ogg (opus) container? LameXP copies cover art when converting into mp3, but omits it in other cases.

**Comment by lordmulder** [comment]
What I actually /can/ do is adding support for cover artwork for Opus 
files, because - in contrast to the Vorbis encoder (OggEnc2) - the Opus 
encoder (OpusEnc) /does/ support an option for embedding cover artwork. 
I see no options regarding ReplayGain though. If you want any features 
to be added to OpusEnc, you'd have to ask the Opus developers, i.e. 
Xiph/Mozilla...

*See also:*
https://mf4.xiph.org/jenkins/view/opus/job/opus-tools/ws/man/opusenc.html

MuldeR

**Comment by lordmulder** [comment]
The *latest* build has cover artwork embedding enabled for the **OpusEnc** encoder:
http://sourceforge.net/projects/lamexp/files/Snapshots%20%28BETA%29/2015-08-19/LameXP-BETA.2015-08-19.Release-Static.Build-1784.exe/download

**Comment by xtemp09** [comment]
Many thanks; embedded art now seems to be working. I know that opusenc doesn't calculate ReplayGain, but it copies ReplayGain from tags of input file when converting by default. ReplayGain (and many others like total number of tracks on disc, disc number, BPM etc.) tags are missing after conversion. =(

**Comment by lordmulder** [comment]
"Retaining" the meta information isn't trivial to. The application, e.g. 
LameXP, must: (a) extract the meta tags from the original input file, 
(b) store the extracted meta infomration internally, and finnally (c) 
re-embed the stored meta information into the re-encoded file - provided 
the selected encoder supports this.

This all would be pretty easy to implement, if we had to deal with only 
one file format. But LameXP support N = 17 input formats and M = 11 
output formats, leading to N x M = 187 combinations that all have to 
work! And of cours each format stores meta tags in its own specific 
format! MP3 doesn't support meta tags at all (though ID3, which now 
exists in various incompatible versions, is the de-dacto standard method 
to store meta tags in MP3), AAC stores meta tags on the MP4 container 
level (and of course Apple/iTunes does it differently than the rest of 
the world), Vorbis and Opus use VorbisComment, Monkeys Audio uses 
ApeTag, and so on...

Consequently, the internal meta data representation of LameXP is kind of 
a "smallest common denominator" of all the various file formats that 
need to be supported...

**Comment by xtemp09** [comment]
I beg to differ; there is always workaround, for example, ffmpeg and MediaInfo. ffmpeg is a small tool if video codecs are excluded during compilation; in the meantime it can have everything on input and produce WAV (and many other formats). MediaInfo is an extremely tiny tool that can read absolutely everything about media files.

I didn't go into the code, but I think that LameXP writes meta tags as Lame does (figured that out from its name). Opus tags - as opusenc, ogg tags - as vorbiscomment and so on. They have already been implemented. Or they can be replaced with ffmpeg, which might be the common denominator that supports all the tags by default.

LameXP is a Swiss knife; usage of common tools like ffmpeg and MediaInfo will make it Wunderwaffle, simplify inner structure and size of the program.

**Comment by lordmulder** [comment]
LameXP is a GUI front-end. In the background the proper CLI encoders or 
decoders are invoked. We already use MediaInfo to detect the file type 
(and thus select the proper decoder) as well as for reading the meta 
tags. But MediaInfo just dumps the meta tags as a list of key-value 
pairs. This needs to be parsed and stored in our internal data structure.

Of course our internal data structur cannot have fields for everytkind 
of info that might exist in some file of some format somewhere on the 
net. Instead we have to restrict to the things the are *commonly* used, 
in all file formats - such as "title", "artist" and "album". Also, 
LameXP needs to have the knowledge which key-value pair found by 
MediaInfo maps to which field of the internal data structure! For 
example, what is called "title=foo" in some files is called just 
"track=foo" in other files, but it all must all go to the "title" field 
of our internal data structur. Same for "artist=bar" and 
"performer=bar", which all has to go to the "artist" field of the 
internal data structure.

Furthermore, the selected output format predetermines which kind of meta 
tag (Id3, VorbisComment, MP4-style meta tags, ApeTag, etc) we must add 
to the file! For example, for MP3 we *must* use ID3, with all the 
implications and limitations that follow from ID3. And it is the 
individual encoder, e.g.  LAME for MP3 or OpusEnc for Opus, which 
predetermines the tags that can be embedded at all (if any).

Finally, LameXP also must know how each tag from the internal data 
structure needs to be passd to the individual encoder. For LAME, e.g., 
the *title* must be passed as "--tt <title>", the *artist* must be 
passed as "--ta <artist>", and so on. At the same time, OpusEnc uses 
"--title <title>", "--artist <artist>", and so on. That's also the 
reason why it wouldn't make sense to have tag type in our internal data 
structure which are *not* supported by all encoders we use (or at least 
by the vast majority of the decoders). It only makes sense to store 
those tags that the encoders actually allow for embedding into the 
re-encoded file.

Regards,
MuldeR

**Comment by xtemp09** [comment]
It's exactly what I meant; inclusion of ffmpeg will unify and simplify that work.

The issue should be closed.

**Comment by lordmulder** [comment]
> It's exactly what I meant; inclusion of ffmpeg will unify and simplify that work.

And it would pretty much mean a complete re-write of the software ;-)

Also I think we use/support at least some encoders/decoders that are **not** in FFmpeg.

**Comment by xtemp09** [comment]
In the meantime, the majority of the encoders is in ffmpeg?

**Comment by lordmulder** [comment]
The majority, yes. But if there is only one "external" encoder we have 
to call separately from FFmpeg, such QAAC or Nero AAC, we again need to 
have the meta data in our own data structure and we again need to know 
how each meta data field has to be passed to the encoder. So, unless 
*everything* is moved into FFmpeg, we don't win much by using FFmpeg.

That plus: Audio filtering capabilities of FFmpeg or pretty minimal. 
Thus, a lot of things in LameXP are done with SoX. So we would need to 
do FFmpeg -> temp.wav -> SoX -> temp2.wav -> FFmpeg, in which case meta 
data is probably lost on the way. We would have to explicitely pass the 
meta tags to be embedded to FFmpeg in the last step. Which is pretty 
much the same "challenge" as before.

Finally, I find it much preferable to be able to update each encoder or 
decoder separately, rather than having one big "monolithic" FFmpeg with 
a zillion of extra libraries included.

**Comment by xtemp09** [comment]
When converting into OPUS I got the following errors.
Though some of them are not related to OPUS, I put them here not to create additional issues.

http://pastebin.com/kzLzLCds
http://pastebin.com/JntjU79m
http://pastebin.com/KNn0yTMC
http://pastebin.com/zzsreAMJ

**Comment by lordmulder** [comment]
**Error 1**
> When converting into OPUS I got the following errors.
> Though some of them are not related to OPUS, I put them here not to create additional issues.
> http://pastebin.com/kzLzLCds
>
>     C:/Users/AMS/AppData/Local/Temp/0c6133a06a101e3e/lxp_opusenc.exe --vbr --comp 10 --framesize 20 --bitrate 96 --title "Towers Of The Void" --artist "Brian Reitzell" --album "Red Riding Hood: Original Motion Picture Soundtrack" --genre Soundtrack --date 2011 --comment tracknumber=1 --picture C:\Users\AMS\AppData\Local\Temp\0c6133a06a101e3e\cad31cc184446b51.jpg C:\Users\AMS\AppData\Local\Temp\0c6133a06a101e3e\4af982e6384aaaa2.wav "F:\Downloads\Temp\music\Soundtracks\OST Red Riding Hood\01 - Brian Reitzell - Towers Of The Void.opus"
>     
>     Error parsing picture option: unable to guess MIME type from file, must set it explicitly

This means that Opus was **not** able to determine the type of your image file. It means your image file is neither a valid JPEG, PNG or GIF file. I could try to set the MIME-Type *explicitly*, to shut up the OpusEnc error. But it would mean that we are embedding an possibly invalid/unsupported image file.

----

**Error 2**
> http://pastebin.com/JntjU79m
> 
>     C:/Users/AMS/AppData/Local/Temp/0c6133a06a101e3e/lxp_opusenc.exe --vbr --comp 10 --framesize 20 --bitrate 96 --title "One Tender Kiss (The Lost Seasons) - Prelude to the Garden of Crystalline Dreams" --artist "Autumn Tears" --album "Love Poems for Dying Children" --genre "Neoclassical Dark Wave" --date 2008 --comment tracknumber=8 --picture C:\Users\AMS\AppData\Local\Temp\0c6133a06a101e3e\54901f7482be10f4.jpg C:\Users\AMS\AppData\Local\Temp\0c6133a06a101e3e\8c08aa41ce8d5e83.wav "F:\Downloads\Temp\music\Darkwave\Autumn Tears\1996 - Love Poems for Dying Children Act I - 13th Anniversary Edition CD1\1996 - Love Poems for Dying Children Act I - CD1\08 - Autumn Tears - One Tender Kiss (The Lost Seasons) - Prelude to the Garden of Crystalline Dreams.opus"
>     
>     F:\Downloads\Temp\music\Darkwave\Autumn Tears\1996 - Love Poems for Dying Children Act I - 13th Anniversary Edition CD1\1996 - Love Poems for Dying Children Act I - CD1\08 - Autumn Tears - One Tender Kiss (The Lost Seasons) - Prelude to the Garden of Crystalline Dreams.opus: No such file or directory
Encoding using libopus 1.1.x-git IA32 [2015-03-26] (audio)

The error "No such file or directory" means that the file you are tying to convert no longer exists. The file probably has been moved, renamed or deleted since you "loaded" it into LameXP.

-----

**Error 3**
> http://pastebin.com/KNn0yTMC
>
>     C:/Users/AMS/AppData/Local/Temp/0c6133a06a101e3e/lxp_faad.exe -o C:\Users\AMS\AppData\Local\Temp\0c6133a06a101e3e\e72299508501f4dc.wav "F:\music\Darkwave\Autumn Tears\1996 - Love Poems for Dying Children Act I - 13th Anniversary Edition CD1\Data\Interview1996.mov"
>      
>     Unable to find correct AAC sound track in the MP4 file.

This MOV/MP4 file corrupted! Either that, or it's an "exotic" kind of MP4 file that FAAD cannot handle. In the latter case, only the FAAD guys can fix it. However, development of FAAD is pretty much dead.

-----

**Error 4**
> http://pastebin.com/zzsreAMJ
>
>     The format of this file is NOT supported:
>     F:/music/Rock/Power metal/Арда/2007 - Море исчезающих времён/data/arda - exorcist.mpg
>     
>     Container Format:       MPEG-PS
As the error message says, *MPEG-PS* files are **not** currently supported! Use [*DGIndex*](http://www.videohelp.com/software/DGMPGDec) to demultiplex the audio from the *video* file. Then you should be able to process it.

**Comment by xtemp09** [comment]
Error 1: It's just a JPEG file; it was embedded with TagScan and is seen by any player.

Error 2: I don't delete files before conversion. My guess is that OPUS encoder doesn't seem to understand long names. I moved the file into another folder with short path, the conversion worked.

Error 3 & 4. The MOV file can be played by every player, even Windows Media player. Could consider an idea of checking procedure when adding files into list? In my opinion, LameXP should have shown a MessageBox that the file is unsupported.

**Comment by lordmulder** [comment]
> Error 1: It's just a JPEG file; it was embedded with TagScan and is seen by any player.

"It's seen by any player" is **not** a prove for a 100% standard-compliant JPEG file. Players are made to deal with all kinds of messed up files that exist on the net. The check in `OpusEnc` might be more *strict*.

Actually the JPEG detection code in OpusEnc looks like this:
>         int is_jpeg(const unsigned char *buf, size_t length){
>             return length>=11&&memcmp(buf,"\xFF\xD8\xFF\xE0",4)==0
>               &&(buf[4]<<8|buf[5])>=16&&memcmp(buf+6,"JFIF",5)==0;
>         }

If you think the above code rejects some *legit* JPEG files, complain to the Opus guys, please ;-)

Anyway, I implemented some changes, so that the MIME type is now passed to the `OpusEnc` explicitly:
[**LameXP-BETA.2015-08-27.Release.Build-1795.zip**](https://www.sendspace.com/file/9xdn1s)

-----

> Error 2: I don't delete files before conversion. My guess is that OPUS encoder doesn't seem to understand long names. I moved the file into another folder with short path, the conversion worked.

Well, it could have happened by accident. But if you think that `OpusEnc` has problems dealing with long file names, then it would be another bug report directed to the Opus guys ;-)

-----

> Error 3 & 4. The MOV file can be played by every player, even Windows Media player. Could consider an idea of checking procedure when adding files into list? In my opinion, LameXP should have shown a MessageBox that the file is unsupported.

MP4/MOV **is** supported by LameXP. Also `MediaInfo` apparently detects *this* file as MP4. Otherwise, LameXP would *reject* the file right away and show an error message. The actual problem here is that `MediaInfo` detects the file as MP4 and thus the file is *accepted*, but later `FAAD` fails to find an audio stream in the file! Of course we can **not** try to decode *any* input file at the moment when it's added to the file list, just because there is the theoretical (but very unlikely) chance that decoding might fail...

**Comment by lordmulder** [comment]
I'm going to consider this issue "done" for now.
