### ISSUE TITLE
gif2apng support or universal X.exe support

### ISSUE THREAD

**Issue by SailorOnDaTea** [lordmulder/LameXP#34]
It is not sound format but can you add  gif2apng support for multithreading? I just want to convert gifs to apng using all cores. By its own gui or CLI with for loop, it will only convert 1 file at a time...

Also, it is more useful if it gives *.apng ext output file instead of *.png (some programs won't recognize animation  but some play when it is *.apng)

you may or may not support options/parameters, it doesn't really matter, since i am ok with defaults. it is a simple exe works like this "gif2apng [options] "filepath\input.gif"

or an universal X program support? user can enter syntax order like {A}{B}{C}...
{A} executable name
{B} parameters
{C} input, output...

**Comment by lordmulder** [comment]
This doesn't fit into LameXP, because it's focused on audio conversion.

Maybe some code from LameXP could be recycled to create a multi-threaded GUI for image conversion, but I currently have no plans for that.

If your program is CLI, you could give [**PPX2**](http://www.pirosa.co.uk/demo/wxargs/wxargs.html) (Windows xargs Clone) a try:
`ir /b *.jpg | ppx2.exe -P 6 D:\FFmpeg\ffmpeg.exe -y -i "{}" "{}.gif"`

**Comment by SailorOnDaTea** [comment]
Thank you! That kind of thing also works for me :+1:
