### ISSUE TITLE
QAAC 2.60 support

### ISSUE THREAD

**Issue by xtemp09** [lordmulder/LameXP#42]
Please add QAAC 2.60 support. The latest (*beta*) version of QAAC supported is 2.58.

**Comment by lordmulder** [comment]
Unless the command-line interface has changed in an incompatible way, you should be able to use QAAC 2.60 with current version of LameXP. Just replace the 2.58 binaries with the 2.60 binaries.

**Comment by xtemp09** [comment]
Been there, tried that. LameXP doesn't see QAAC 2.60. At least, that happened with the beta.

**Comment by lordmulder** [comment]
Can you please run LameXP with option `--console` (i.e. start a terminal, change to LameXP directory and type `LameXP.exe --console`) and check out the messages that appear in the log window?

**Comment by lordmulder** [comment]
xtemp09,

I have uploaded a new **QAAC Add-in** for LameXP, which is now based on QAAC v2.61:
[`LameXP.qaac-addin.2016-10-03.zip`](https://sourceforge.net/projects/lamexp/files/Miscellaneous/Add-ins/qaac/LameXP.qaac-addin.2016-10-03.zip/download)

For me this is detected by the current version of LameXP just fine. So please try again with **this** *QAAC Add-in* version. And please follow the install instructions in README accurately!

-----

If you encounter any problems, the first thing to do is running `qaac.exe --check` from LameXP directory in order to make sure that the Apple AAC Encoder is recognized correctly. If everything is fine, the next thing to do is running `LameXP.exe --console` and look at the console output.

**Comment by xtemp09** [comment]
Hello, it seems to be working. Thanks!

> Enabled QAACx64 encoder v2.61.

**Comment by lordmulder** [comment]
Fine!
