### ISSUE TITLE
Encode quality setting GUI: a few fuzzy things that could be improved

### ISSUE THREAD

**Issue by maiko1** [lordmulder/LameXP#47]
Hello, here comes a bunch of improvements suggestions. :)

1. Under the Compression tab, some of the codecs bit rate are missing, instead there is a fuzzy slider graded something like 0, 1, 2... etc
For MP3 there are a lower and an upper limit given in kbps on vast majority of encoders which allows the user to set it freely with precise control, perhaps the developer could preferably add two sliders, one for upper kbps limit and one for lower kbps limit?

2. Compared to other codec quality settings, the MP3 Slider has inverse numbering of the quality rate, 
Minimum = Quality Level 9, and Maximum = Quality Level 0, 
I guess this should be the opposite, but much more preferred have all gradings in kbps instead of apparent unspecified "quality number".

3. Perhaps add even a third slider for quality settings for those who want it and/or don't know how to use upper and lower kbps setting for VBR.
A suggestion is to synchronize the quality slider with the upper and lower kbps slider, that will allow the user to see and learn what the quality settings does with respect to kbps settings.

4. Synchronize the slider for each codec so when one is switching between VBR, ABR and CBR one doesn't have to make a lots of fiddling everywhere, it's a bit unconventional Windows GUI behavior.

5. Opus VBR slider shows only one value in ~kbps, how does the encoder decide what upper and lower limits are to be used, and where can we read more about what kbps settings is behind the quality number for all codecs used?

6. Opus codec quality setting slider has maximum 256 kbps while the specification allows up to 510 kbps, may we have this option available?
https://en.wikipedia.org/wiki/Opus_%28codec%29

7. Can I specify Opus 510 kbps under the Advanced Options tab -> Custom Encoder Options?

I didn't check very thoroughly so these are just the ones I saw immediately.
Thank you very much for the most part a good GUI.

**Comment by lordmulder** [comment]
> Under the Compression tab, some of the codecs bit rate are missing, instead there is a fuzzy slider graded something like 0, 1, 2... etc
For MP3 there are a lower and an upper limit given in kbps on vast majority of encoders which allows the user to set it freely with precise control, perhaps the developer could preferably add two sliders, one for upper kbps limit and one for lower kbps limit?

In **CBR** or **ABR** mode, you select the desired _target bitrate_. For the MP3 format, only a few *pre-defined* bitrates are actually possible. Please See [*here*](https://en.wikipedia.org/wiki/MP3#Bit_rate) for a complete list. You can **not** have other bitrates in MP3 format! In "VBR" MP3's you can have a mix of frames with *different* bitrates, so **in average** (for the whole file) you can have other bitrates - still, each MP3 frame in the file needs to be one of the pre-defined bitrates!

> Compared to other codec quality settings, the MP3 Slider has inverse numbering of the quality rate,
Minimum = Quality Level 9, and Maximum = Quality Level 0,
I guess this should be the opposite, but much more preferred have all gradings in kbps instead of apparent unspecified "quality number".

If you select **VBR** mode (quality-based variable bitrate), the slider selects _target quality_. This is in whatever scale that the individual encoder developers have defined for their encoder. For example, with the LAME MP3 encoder, VBR quality is simply an integer value, in the **0** (best quality) to **9** (worst quality) range. See [*here*](http://lame.cvs.sourceforge.net/viewvc/lame/lame/doc/html/usage.html).

> Synchronize the slider for each codec so when one is switching between VBR, ABR and CBR one doesn't have to make a lots of fiddling everywhere, it's a bit unconventional Windows GUI behavior.

I don't think it's a good idea to "synchronize" the sliders between different formats, because bitrates are absolutely **not** comparable between different formats. For example, a 96 kbps MP3 music file is horrible quality, a 96 kbps AAC music file may be quite okay, and a 96 kbps Opus music file is usually quite good.

> Opus VBR slider shows only one value in ~kbps, how does the encoder decide what upper and lower limits are to be used, and where can we read more about what kbps settings is behind the quality number for all codecs used?

That's just how the Opus developers decided to design the *interface* of their encoder. As said before, LAME defines VBR quality as am integer value in 0 to 9 range. Opus does it differently: it defines VBR quality as a "nominal" bitrate. Opus still does *real* VBR encoding, but simply uses a different notion of "quality level".

> Opus codec quality setting slider has maximum 256 kbps while the specification allows up to 510 kbps, may we have this option available?

The Opus encoder specifies the _target bitrate_ as a value in 6 kbps to 256 kbps range. See [*here*](https://mf4.xiph.org/jenkins/view/opus/job/opus-tools/ws/man/opusenc.html#--bitrate). I think this is meant as "per channel". 510 kbps may be the overall limit, across *all* audio channels.

Regards,
MuldeR
