### ISSUE TITLE
WebM container support

### ISSUE THREAD

**Issue by imgiling** [lordmulder/LameXP#51]
Downloading Opus audio with youtube-dl results in Opus stream inside WebM container as it is served this way from Youtube. Unfortunately such files can't be imported in LameXP as it doesn't support WebM container. Can you please add support for it? Of course I'll donate. :)
Also an interesting question would be - could LameXP support just repacking from WebM to OGG without transcoding?

**Comment by lordmulder** [comment]
WebM is a **video** file standard. It is Google's VP9 video format _multiplexed_ with Opus audio and wrapped in a Matroska container. The "official" Opus decoder from Xiph.org, which is used by LameXP, doesn't support Matroska container to the best of my knowledge. Xiph.org uses their own "Ogg" container.

**Comment by imgiling** [comment]
As far as I understand WebM is a container with a subset of Matroska features. [webm stands for Web Media (not Web Matroska). It is a subset of Matroska with only the necessary features required for video (and audio) to play over the web.](https://www.matroska.org/news/webm-matroska.html)

My question can become more generic then - does LameXP support Matroska container as input? I am not sure how LameXP works internally, but I doubt it uses the "official" Opus decoder from Xiph.org directly. For example when the input file is MP3 and the output uses the Opus codec, it should decode the MP3 first. I imagine it uses ffmpeg to do so and ffmpeg supports Matroska as an input format.

**Comment by lordmulder** [comment]
**LameXP** is a _GUI front-end_ for a variety of audio encoders (LAME, Vorbis, Opus, etc) and even more audio decoders. So your question is misleading. LameXP _does_ support the Opus audio format, for encoding (output) as well as decoding (input). Opus support is provided by [**opus-tools**](https://opus-codec.org/downloads/), which is the "official" Opus encoder/decoder software provided by Xiph.org, the creators of Opus format.

**Comment by imgiling** [comment]
How is decoding related to the codec used for encoding? For example opus-tools's opusenc supports only "WAV, AIFF, FLAC, Ogg/FLAC, or raw files" as input. If the input is ACC or MP3, LameXP should decode it first to WAV before feeding it to opusenc.

**Comment by lordmulder** [comment]
> How is decoding related to the codec used for encoding? For example opus-tools's opusenc supports only "WAV, AIFF, FLAC, Ogg/FLAC, or raw files" as input. If the input is AAC or MP3, LameXP should decode it first to WAV before feeding it to opusenc.

Yeah, and that's exactly what is done :smirk:

The format of the input file is detected, via _MediaInfo_ and then the proper decoder tool is selected. For example, if an MP3 file is detected, it will be decoded to WAV using *mpg123* tool. If an AAC file is detected, it will be decoded to WAV using *faad* tool. If a FLAC file is detected, it will be decoded to WAV using *flac* tool. If an Opus file is detected, it will be decoded to WAV using _opus-tools_ suite. And so on...

Opus tools does **not** support MKV container, only Ogg container - which is the "native" container for Opus audio format. Surely, we could integrate *MKVToolNix* to extract the tracks from MKV container. But an MKV file may contain pretty much **anything**. This would require a completely new strategy! Instead of detecting the file format _once_ and then let the proper tool decode the file, we would need to implement "recursive" decoding: Detect the format of the file, then invoke the proper tool to extract the tracks from container, then detect the format of the *extracted* files, then invoke the proper tool to decode the *extracted* files. But this would be a rather big change of how the program works. Also there are many open questions: What if the "extracted" track again is in some container format that the decoder can not handle directly? What if there are many audio tracks in the, e.g., MKV container - maybe in different audio formats?

**Comment by imgiling** [comment]
I understand. Thank you for explaining the process. Now I see why implementing recursive decoding to handle MKV will require a lot of work . Thank you for your time. I suppose the issue can be closed now.
