### ISSUE TITLE
please make #14 an issue

### ISSUE THREAD

**Issue by pupvogel** [lordmulder/LameXP#58]
Hi,
I just came across the behaviour that was reported in #14.
This behaviour was really unexpected, because in my case, most subdirectories were included, but some were not - just because there was a file in the first level directory.
Would be cool if there was a setting for this.
Thanks !! 8o)
Best
Ken

**Comment by lordmulder** [comment]
Hello.

Since we already have a distinct menu item to add a directory _non-recursively_ and another distinct menu item to add a whole directory tree _recursively_, I think additionally having an option that makes the "non-recursive" mode behave like the "recursive" one would not only be redundant but also kind of silly.

Also I think that having only **one** menu item for both, and instead using an _option_ to switch between "non-recursive" and "recursive" mode would be less intuitive. And annoying, if you have to switch often.

If people think that the current behavior of the "non-recursive" mode – will descend **one** level _if and only if there are **zero** files on the current level_ – is too confusing, I'd rather remove that "feature".

**Comment by pupvogel** [comment]
Hi,

wow, how can a suggestion be silly that obviously intends to make your software more intuitive.

Out of the box, the program SEEMS to take in all the folders with subfolders that you drop on it.
But it doesn't, it filters out SOME subfolders based on some weird check (that at least I and the author of #14 don't get). How could anyone expect this to happen before running into trouble..?

The extra menu-driven recursive mode (that I found after getting into that trouble) also forces me to create a special folder containing only the folders that I want to encode.
That's not necessary when doing drag-and-drop.

Thank you for your kind consideration.

**Comment by lordmulder** [comment]
As said before, we already have distinct menu items to add a directory _recursively_ or _non-recursively_. So you already can do both – _**without**_ the need for another option. Adding an option that makes _non-recursively_ mode behave like _recursively_ mode would be "silly", because with such an option enabled, we then would have two menu items that do the exactly same thing – despite suggesting something else.

What seems to be the **_real_** point of confusion is that even the _non-recursively_ mode – and Drag&Drop is nothing but a shortcut for that – will descend **one** level in the directory tree _if and only if there are **zero** files in the selected directory_. I thought that this "feature" would be a good idea – since the alternative in that particular case would be adding **no** file at all. But if this **_seemingly_** inconsistent behavior confuses many people, then I'd rather remove that, instead of disimproving things with yet another option...

Regards,
MuldeR

**Comment by lordmulder** [comment]
Fixed in 3bcf6a686aede183ec501da813e819d83cc9bf49.
