### ISSUE TITLE
Trying to run LameXP and have it use "cache" folder not working

### ISSUE THREAD

**Issue by Gamemoose** [lordmulder/LameXP#90]
Hello!

I've been having people try LameXP for converting MP4 files to WAV for dictation and the program works great!  It's very easy for those folks to use.  Unfortunately, the antivirus the company uses is stating that the executables that are put in the c:\users\[user\appdata\local\temp\[random folder] is a virus.  I know it's not a virus however due to best practice, I can't have the anti-virus not scan those temp folders.  I'm using 4.18 (build 2240).

I read another person's question about a "Security issue" from back in 2015.  In it you said that one could create a folder called "cache".  What binaries do I copy into that folder?  Copying the created executables in the Temp folder didn't work and I've tried different files from the source I downloaded from GitHub.  Could you tell me what files I need to copy into the Cache folder to get LameXP to run the necessary files from that folder rather than the temp?

Thanks!

**Comment by lordmulder** [comment]
> I read another person's question about a "Security issue" from back in 2015. In it you said that one could create a folder called "cache". What binaries do I copy into that folder? Copying the created executables in the Temp folder didn't work and I've tried different files from the source I downloaded from GitHub. Could you tell me what files I need to copy into the Cache folder to get LameXP to run the necessary files from that folder rather than the temp?

You have to put **all** files with the _original file name_, as they are found in the source tree:
https://github.com/lordmulder/LameXP/tree/master/res/tools

When LameXP automatically extracts the files to the TEMP directory, then it will _only_ extract the "variant" of each files that matches to your CPU. But if you provide the files in **`cache`** folder, you have to provide ***all*** the "variants", because it is not known beforehand which one is going to be used...

I just re-verified that it is working as expected:
![lamexp_cache](https://user-images.githubusercontent.com/470590/78400105-5fed1900-75f6-11ea-90ce-b3df8fe8e2ef.jpg)

Regards
MuldeR

**Comment by Gamemoose** [comment]
There we go!  I'm not sure if I had the right files (I grabbed the files from MASTER, though I'm not sure if that works for 4.18 or not) or the fact I saw the folder appear in my temp folder and I thought it didn't work.  With your explanation, I understood better what was going on.

Thanks for the quick reply!

**Comment by lordmulder** [comment]
> There we go! I'm not sure if I had the right files (I grabbed the files from MASTER, though I'm not sure if that works for 4.18 or not)

Be sure to grab the files that match exactly your version, otherwise hash check will fail.

Files for **v4.18** release:
https://github.com/lordmulder/LameXP/tree/Release_418/res/tools
