### ISSUE TITLE
VirusTotal: 3 engines detected this file as malicious

### ISSUE THREAD

**Issue by davehoo** [lordmulder/LameXP#92]
SecureAge APEX - Malicious
Zillya - Trojan.Droma.Win32.1396
VBA32 - BScope.Trojan.Agent

https://www.virustotal.com/gui/file/6452f3d27497b17590de9a889430b7f3a267ad48f1f8a34ea99d39447f8cc72f/detection

So, what's up with that?

**Comment by lordmulder** [comment]
**Please read this:**
* http://muldersoft.com/#info
* http://muldersoft.com/#so-much-about-qa

Even though 3 "detections" (_false positive_) is below the noise threshold, you still may wish to report the problem to the "anti-virus" vendor, so that _they_ can fix the **bug** that exists in _their_ software.

Regards.
